version: '3.3'

services:
  app:
    build: ./
    restart: always
    container_name: messaggioapp
    ports:
      - 8090:8090
    depends_on:
      - zookeeper
      - postgres
    volumes:
      - ./config.json:/app/config.json

  postgres:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: messaggiodb
    environment:
      POSTGRES_DB: messaggio
      POSTGRES_PASSWORD: postgres@
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/main
      DATABASE_URL: postgresql://postgres:postgres@@messaggiodb:5432/messaggio?serverVersion=15&charset=utf8
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      #- /var/lib/postgresql/15/main:/var/lib/postgresql/data:rw
      - ./database:/var/lib/postgresql/data
      - ./database/main:/var/lib/postgresql/data
      - /var/run/postgresql:/var/run/postgresql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - kafka-network
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - kafka-network
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
      KAFKA_BROKER_ID: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1

networks:
  kafka-network:
    driver: bridge